-- MySQL Script generated by MySQL Workbench
-- Mon Mar  7 20:00:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema culAmpolla
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `culAmpolla` ;

-- -----------------------------------------------------
-- Schema culAmpolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culAmpolla` DEFAULT CHARACTER SET utf8 ;
USE `culAmpolla` ;

-- -----------------------------------------------------
-- Table `culAmpolla`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culAmpolla`.`proveidor` (
  `NIF` VARCHAR(10) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `pis` INT NULL,
  `porta` VARCHAR(45) NULL,
  `codiPostal` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NIF_UNIQUE` ON `culAmpolla`.`proveidor` (`NIF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `culAmpolla`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culAmpolla`.`ulleres` (
  `idUlleres` INT NOT NULL auto_increment,
  `marca` VARCHAR(45) NULL,
  `gaduacio` VARCHAR(45) NULL,
  `TipusMuntura` enum('flotant','pasta','metàl·lica'),
  `colorVidre` VARCHAR(45) NULL,
  `proveidor_NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUlleres`),
  CONSTRAINT `fk_ulleres_proveidor1`
    FOREIGN KEY (`proveidor_NIF`)
    REFERENCES `culAmpolla`.`proveidor` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ulleres_proveidor1_idx` ON `culAmpolla`.`ulleres` (`proveidor_NIF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `culAmpolla`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culAmpolla`.`clients` (
  `NIF` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dataRegistre` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `idReferencia` INT,
  PRIMARY KEY (`NIF`),
  foreign key ( `idReferencia`) references `clients` (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culAmpolla`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culAmpolla`.`empleats` (
  `idEmpleat` INT NOT NULL AUTO_INCREMENT,
  `nomEmpleat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culAmpolla`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culAmpolla`.`compra` (
  `clients_NIF` INT NOT NULL,
  `ulleres_idUlleres` INT NOT NULL,
  `idEmpleat` INT NOT NULL,
  `data` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`clients_NIF`, `ulleres_idUlleres`, `idEmpleat`),
  CONSTRAINT `fk_clients_has_ulleres_clients`
    FOREIGN KEY (`clients_NIF`)
    REFERENCES `culAmpolla`.`clients` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_has_ulleres_ulleres1`
    FOREIGN KEY (`ulleres_idUlleres`)
    REFERENCES `culAmpolla`.`ulleres` (`idUlleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_empleats1`
    FOREIGN KEY (`idEmpleat`)
    REFERENCES `culAmpolla`.`empleats` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_clients_has_ulleres_ulleres1_idx` ON `culAmpolla`.`compra` (`ulleres_idUlleres` ASC) VISIBLE;

CREATE INDEX `fk_clients_has_ulleres_clients_idx` ON `culAmpolla`.`compra` (`clients_NIF` ASC) VISIBLE;

CREATE INDEX `fk_compra_empleats1_idx` ON `culAmpolla`.`compra` (`idEmpleat` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
