-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 12:13:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzeria` ;

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `idprovincia` INT NOT NULL AUTO_INCREMENT,
  `nomprovincia` VARCHAR(45) NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localitat` (
  `idlocalitat` INT NOT NULL AUTO_INCREMENT,
  `localitat` VARCHAR(45) NULL,
  `provincia_idprovincia` INT NOT NULL,
  PRIMARY KEY (`idlocalitat`),
  INDEX `fk_localitat_provincia1_idx` (`provincia_idprovincia` ASC) VISIBLE,
  CONSTRAINT `fk_localitat_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `pizzeria`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `cognoms` VARCHAR(45) NULL,
  `adreça` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  `localitat_idlocalitat` INT NOT NULL,
  PRIMARY KEY (`idclient`),
  INDEX `fk_client_localitat_idx` (`localitat_idlocalitat` ASC) VISIBLE,
  CONSTRAINT `fk_client_localitat`
    FOREIGN KEY (`localitat_idlocalitat`)
    REFERENCES `pizzeria`.`localitat` (`idlocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Botiga` (
  `idBotiga` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Adreça` VARCHAR(45) NULL,
  `codigPostal` VARCHAR(45) NULL,
  `localitat_idlocalitat` INT NOT NULL,
  PRIMARY KEY (`idBotiga`),
  INDEX `fk_Botiga_localitat1_idx` (`localitat_idlocalitat` ASC) VISIBLE,
  CONSTRAINT `fk_Botiga_localitat1`
    FOREIGN KEY (`localitat_idlocalitat`)
    REFERENCES `pizzeria`.`localitat` (`idlocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandes` (
  `idcomandes` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `tipusComanda`ENUM('local', 'domicili', 'recollida'),
  `detallComanda` VARCHAR(100) NULL COMMENT 'Quanitat de products per tipus, ex: 3 hamburgueses, 1 pizza, 4 refresc',
  `preuTotal` DOUBLE NULL,
  `client_idclient` INT NOT NULL,
  `Botiga_idBotiga` INT NOT NULL,
  `idRepartidor` INT NULL,
  `horaEntrega` DATETIME NULL,
  PRIMARY KEY (`idcomandes`),
  INDEX `fk_comandes_client1_idx` (`client_idclient` ASC) VISIBLE,
  INDEX `fk_comandes_Botiga1_idx` (`Botiga_idBotiga` ASC) VISIBLE,
  CONSTRAINT `fk_comandes_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `pizzeria`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comandes_Botiga1`
    FOREIGN KEY (`Botiga_idBotiga`)
    REFERENCES `pizzeria`.`Botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`CategoriaPizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`CategoriaPizza` (
  `idCategoriaPizza` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoriaPizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Productes` (
  `idProductes` INT NOT NULL AUTO_INCREMENT,
  `NomProducte` VARCHAR(45) NULL,
  `Preu` DOUBLE NULL,
  `tipusProducte` ENUM('pizza', 'beguda', 'hamburguesa'),
  `CategoriaPizza_idCategoriaPizza` INT NULL,
  PRIMARY KEY (`idProductes`),
  INDEX `fk_Productes_CategoriaPizza1_idx` (`CategoriaPizza_idCategoriaPizza` ASC) VISIBLE,
  CONSTRAINT `fk_Productes_CategoriaPizza1`
    FOREIGN KEY (`CategoriaPizza_idCategoriaPizza`)
    REFERENCES `pizzeria`.`CategoriaPizza` (`idCategoriaPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`ProductesComandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`ProductesComandes` (
  `comandes_idcomandes` INT NOT NULL,
  `Productes_idProductes` INT NOT NULL,
  `quantitat` INT NOT NULL,
  PRIMARY KEY (`comandes_idcomandes`, `Productes_idProductes`),
  INDEX `fk_ProductesComandes_Productes1_idx` (`Productes_idProductes` ASC) VISIBLE,
  CONSTRAINT `fk_ProductesComandes_comandes1`
    FOREIGN KEY (`comandes_idcomandes`)
    REFERENCES `pizzeria`.`comandes` (`idcomandes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductesComandes_Productes1`
    FOREIGN KEY (`Productes_idProductes`)
    REFERENCES `pizzeria`.`Productes` (`idProductes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Empleats` (
  `idEmpleats` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Cognoms` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `Telf` VARCHAR(45) NULL,
  `tipusTreballador` ENUM('cuiner', 'repartidor'),
  `Botiga_idBotiga` INT NOT NULL,
  PRIMARY KEY (`idEmpleats`),
  INDEX `fk_Empleats_Botiga1_idx` (`Botiga_idBotiga` ASC) VISIBLE,
  CONSTRAINT `fk_Empleats_Botiga1`
    FOREIGN KEY (`Botiga_idBotiga`)
    REFERENCES `pizzeria`.`Botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
